### ISSUE TITLE
get_seismic_labels() is hardcoded to have just 6 colors - better user experience of using custom number of classes

### ISSUE THREAD

**Issue by sharatsc** [microsoft/seismic-deeplearning#145]
Will fail on datasets that have more than 6 labels

**Comment by maxkazmsft** [comment]
Also clean up this code
def get_seismic_labels():
    return np.asarray(
        [[69, 117, 180], [145, 191, 219], [224, 243, 248], [254, 224, 144], [252, 141, 89], [215, 48, 39]]
    )


@curry
def decode_segmap(label_mask, n_classes=6, label_colours=get_seismic_labels()):
    """Decode segmentation class labels into a colour image
    Args:
        label_mask (np.ndarray): an (N,H,W) array of integer values denoting
            the class label at each spatial location.
    Returns:
        (np.ndarray): the resulting decoded color image (NCHW).
    """
    r = label_mask.copy()
    g = label_mask.copy()
    b = label_mask.copy()
    for ll in range(0, n_classes):
        r[label_mask == ll] = label_colours[ll, 0]
        g[label_mask == ll] = label_colours[ll, 1]
        b[label_mask == ll] = label_colours[ll, 2]
    rgb = np.zeros((label_mask.shape[0], label_mask.shape[1], label_mask.shape[2], 3))
    rgb[:, :, :, 0] = r / 255.0
    rgb[:, :, :, 1] = g / 255.0
    rgb[:, :, :, 2] = b / 255.0
    return np.transpose(rgb, (0, 3, 1, 2))

To use just the generic matplotlib colormap

**Comment by yalaudah** [comment]
Also, in `test.py`, there is a duplicate function of `decode_segmap` that should be removed. There might be other instances of duplicate functions that we need to fix as well. Here's tge duplicate function: 

```python 
@curry
def to_image(label_mask, n_classes=6):
    label_colours = get_seismic_labels()
    r = label_mask.copy()
    g = label_mask.copy()
    b = label_mask.copy()
    for ll in range(0, n_classes):
        r[label_mask == ll] = label_colours[ll, 0]
        g[label_mask == ll] = label_colours[ll, 1]
        b[label_mask == ll] = label_colours[ll, 2]
    rgb = np.zeros((label_mask.shape[0], label_mask.shape[1], label_mask.shape[2], 3))
    rgb[:, :, :, 0] = r
    rgb[:, :, :, 1] = g
    rgb[:, :, :, 2] = b
    return rgb
```

**Comment by yalaudah** [comment]
I will also add that the `self.n_classes` in the `PatchLoader` class is also hard-coded to 6 classes. That should be changed as well.
