### ISSUE TITLE
patch_size parameter in config file not used in staging branch

### ISSUE THREAD

**Issue by yalaudah** [microsoft/seismic-deeplearning#164]
The config files have a parameter for the `patch_size`, but its not used in the staging branch to create training patches. 

Prerequisites: #162

**Comment by kirasoderstrom** [comment]
https://github.com/microsoft/seismic-deeplearning/blob/staging/scripts/prepare_dutchf3.py 

In the staging branch patch is not used to create the crosslines or inlines but it is in the master branch. When using this script the indecies generated in the txt files seem to be past our data dimension boundaries. 

![image](https://user-images.githubusercontent.com/8856246/73969630-a5c88200-48d0-11ea-9851-96c27f3e80d3.png)

Also see below it seems that the first patch highlighted is being used, but the second is not actually being used in the script. Perhaps while this is being worked on, there can be a new naming convention to avoid using the same word here?

![image](https://user-images.githubusercontent.com/8856246/73969509-6e59d580-48d0-11ea-9930-746da56e2ff1.png)

**Comment by yalaudah** [comment]
Closing this issue since it was addressed in PR #185
