### ISSUE TITLE
Rename patch to patch_size to avoid confusion

### ISSUE THREAD

**Issue by yalaudah** [microsoft/seismic-deeplearning#182]
`patch` by itself can refer to many different things (type of model: patch vs. section, or an actual patch extracted from a 2D section). To avoid confusion, we should at least rename `patch` to `patch_size` in files like `prepare_dutchf3.py` where it is clear `patch` is meant as `patch_size`.

See Kira's comment here: https://github.com/microsoft/seismic-deeplearning/issues/164.

**Comment by squassina** [comment]
Fixed in PR #200
