### ISSUE TITLE
Update patch to patch_size in ablation.sh and README.md

### ISSUE THREAD

**Issue by kirasoderstrom** [microsoft/seismic-deeplearning#189]
Update patch to patch_size in ablation.sh and README.md

This was attempted to be resolved in #185 although when it was pushed the build kept failing. This task includes investigating why the build is not completing and then updating the respective files to print patch_size when referring to patch_size.

**Comment by squassina** [comment]
Closed in [PR #200 ](https://github.com/microsoft/seismic-deeplearning/pull/200)
