### ISSUE TITLE
interpret the padding and validation set mIoU vs predictoins - currently the quality of output predictions doesn't match the mIoU metric

### ISSUE THREAD

**Issue by maxkazmsft** [microsoft/seismic-deeplearning#230]
mIoU of these looks like .90 yet we're quoting above .985.
 
Visualization during training (last step) on validation:
![](https://deepseismicsharedstore.blob.core.windows.net/sharedgithubcontent/MicrosoftTeams-image%20(1).png)

mIoU is above 0.985
![](https://deepseismicsharedstore.blob.core.windows.net/sharedgithubcontent/MicrosoftTeams-image%20(2).png)

**Comment by yalaudah** [comment]
Fixed in #264
