### ISSUE TITLE
snapshot ignite dev version - enables to continue running on dev version of ignite if goes obsolete

### ISSUE THREAD

**Issue by maxkazmsft** [microsoft/seismic-deeplearning#252]

**Comment by vfdev-5** [comment]
Hi @maxkazmsft , we recently found this repository as one that build on ignite. Thanks for using Ignite !
We are planning to release v0.4.0 version between May 15-25 where we fix recent bugs with Engine and added a lot of other features. We hope to make most of things backward compatible. However, some of the features of v0.3.0 wont be supported. Feel free to contact us if you need a support on migration to the newest version or current nightly release. The simpliest way to reach out us is to fill a question issue:  https://github.com/pytorch/ignite/issues/new/choose
