### ISSUE TITLE
run master and provide feedback on state of the repo - makes repo friendly to new users

### ISSUE THREAD

**Issue by maxkazmsft** [microsoft/seismic-deeplearning#315]
The ask is to run the repo from the latest master branch and provide feedback regarding user-friendliness, bugs, overall correctness, approaches, etc

**Comment by fazamani** [comment]
https://microsoft.sharepoint.com/:p:/t/MLBostonLondonADS/EfP4qb62m7lLp3z_iaUoohkBBsy-Y1SMmdpulm2i7FwMBg?e=Pre1vc
