### ISSUE TITLE
add correctness data and class size unit test metrics - facilitates certainty in correct data flow

### ISSUE THREAD

**Issue by maxkazmsft** [microsoft/seismic-deeplearning#317]
add performance metrics similar to test/cicd/src/check_performance.py  to check whether the input data and predicted results on synthetic checkerboard dataset have the correct dimensions, etc - this essentially checks the correctness of data flow through the project

Checking data sizes only - not distributions

- number of classes - training, prediction
- length of dataset
- length of data loader

Pre-requisit #346

**Comment by fazamani** [comment]
add a test to check the bounds (limits) on the data
