### ISSUE TITLE
image normalization should be wrt the volume image - facilitates correctly displayed image colormap range

### ISSUE THREAD

**Issue by fazamani** [microsoft/seismic-deeplearning#342]
The way we normalize the image before saving to disk,

![image](https://user-images.githubusercontent.com/26488238/83685494-62e09780-a5ae-11ea-8fdc-9451bcac4708.png)

is relative to each image, which causes the following

![image](https://user-images.githubusercontent.com/26488238/83684329-7db20c80-a5ac-11ea-9bc0-b320202dd984.png)

labels are changing, but images are "mapped" to the same color! This might be only relevant to data, in which all pixel values in each segmented image are taking two unique values, but overall in the volume we have more unique values for the pixels.

Hence, the normalization should be wrt a global range in the volume of data.

**Comment by yalaudah** [comment]
Also, this issue should address the problem where the normalized image is a constant image resulting in diving by zero, and saving NaNs to disk. We should:

- [ ] Only use the dataset min and max to normalize
- [ ] Assert that the min and max are *not* equal, otherwise we would divide by zero
