### ISSUE TITLE
Add docker tests - ensures docker image doesn't break while new features are added

### ISSUE THREAD

**Issue by yalaudah** [microsoft/seismic-deeplearning#358]
Add a new job (in parrallel with the setup job) to build and run the docker image. We can do this this for both local and distributed train, in addition to running the notebooks and testing a pretrained model.

**Comment by fazamani** [comment]
Due to time constraint and hardware limitation (build VM has single GPU), this issue is de-scoped to the following:
- Add a job daisy-changed to the last job in the main_build  to test that the docker builds successfully.
- We will revisit the parallel jobs run in a later time.

@maxkazmsft
