### ISSUE TITLE
Suggested improvements to HRNet notebook, facilitates better UX

### ISSUE THREAD

**Issue by vapaunic** [microsoft/seismic-deeplearning#62]
[from Patrick]
In HRNet_demo_notebook: 

- [ ] might be that the last two tensorboard command should be before training, so that training progress gets shown (otherwise I think it won't run the last two lines until the training is done). 
- [ ] could contain more high-level info, and generally if it's meant as the first thing for the user to execute then this notebook could be a bit more visually appealing. 
- [ ] could add instructions how people can bring their own dataset 
- [ ] Could visualize what the results of the trained model look like, and maybe how to save (so that can be deployed later) 
- [ ] Training takes a long time, could point out how long or print how many epochs it's running  
- [ ] Is  there a way to see how the model performs (eg visually) without having to wait for the training to finish

**Comment by maxkazmsft** [comment]
Make HRNet more fragile overall

**Comment by maxkazmsft** [comment]
no longer applicable - partly done
